# Generated by Django 4.2.4 on 2023-11-11 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.college')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20)),
                ('staff_role', models.CharField(choices=[('CEO', 'CEO'), ('Director', 'Director'), ('AO', 'AO'), ('Principal', 'Principal'), ('CFO', 'CFO'), ('Estate Manager', 'Estate Manager'), ('Security', 'Security'), ('Warden', 'Warden'), ('Receptionist', 'Receptionist'), ('NCC Staff', 'NCC Staff'), ('PE Staff', 'PE Staff'), ('Instution Staff Other', 'Instution Staff Other'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Teaching Staff Other', 'Teaching Staff Other'), ('Lab Instructor', 'Lab Instructor'), ('Librarian', 'Librarian'), ('Library Assistant', 'Library Assistant'), ('Placement Officer', 'Placement Officer'), ('Office Assistant', 'Office Assistant'), ('Supervisor', 'Supervisor'), ('Admission Staff', 'Admission Staff'), ('Office Staff', 'Office Staff'), ('Non Teaching Staff Other', 'Non Teaching Staff Other')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(default='/user.png', upload_to='profile_images')),
                ('colege', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.college')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
