# Generated by Django 4.2.7 on 2023-11-15 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='colege',
            new_name='college',
        ),
    ]
