# Generated by Django 4.2.7 on 2023-11-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_rename_colege_profile_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='staff_role',
            field=models.CharField(max_length=30),
        ),
    ]
