# Generated by Django 4.2.7 on 2023-11-18 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0005_alter_profile_staff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role_type', models.CharField(choices=[('CEO', 'CEO'), ('Director', 'Director'), ('AO', 'AO'), ('Principal', 'Principal'), ('CFO', 'CFO'), ('Teaching', 'Teaching'), ('Non-teaching', 'Non-teaching'), ('Institution-staff', 'Institution-staff')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='staff_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.roles'),
        ),
    ]
