# Generated by Django 4.2.7 on 2023-11-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_profile_image_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
