# Generated by Django 4.2.7 on 2023-11-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
