# Generated by Django 4.2.7 on 2023-11-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_leavedata_leaveapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='profile',
            name='leaves_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_leaves',
            field=models.IntegerField(default=12),
        ),
        migrations.DeleteModel(
            name='LeaveData',
        ),
    ]
