# Generated by Django 4.2.7 on 2023-11-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_alter_roles_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='approved_AO',
            field=models.BooleanField(default=False),
        ),
    ]
