# Generated by Django 4.2.7 on 2023-11-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_leaveapplication_approved_ao'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='ao_approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
