# Generated by Django 4.2.7 on 2023-11-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0023_leaveapplication_ao_approval_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='ao_approval_timestamp',
            new_name='AO_approval_timestamp',
        ),
    ]
