# Generated by Django 4.2.7 on 2023-11-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0024_rename_ao_approval_timestamp_leaveapplication_ao_approval_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_AO',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_ceo',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_director',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_hod',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_principal',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
