# Generated by Django 4.2.7 on 2023-11-25 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0025_alter_leaveapplication_approved_ao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='staff_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='user_app.roles'),
        ),
    ]
