# Generated by Django 4.2.7 on 2023-11-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0026_alter_profile_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_AO',
            field=models.BooleanField(blank=True, default=django.db.models.deletion.SET_NULL, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_ceo',
            field=models.BooleanField(blank=True, default=django.db.models.deletion.SET_NULL, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_director',
            field=models.BooleanField(blank=True, default=django.db.models.deletion.SET_NULL, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_hod',
            field=models.BooleanField(blank=True, default=django.db.models.deletion.SET_NULL, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_principal',
            field=models.BooleanField(blank=True, default=django.db.models.deletion.SET_NULL, null=True),
        ),
    ]
