# Generated by Django 4.2.7 on 2023-11-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0029_alter_leaveapplication_approved_ao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='letter',
            field=models.FileField(blank=True, default=None, upload_to='letters/'),
        ),
    ]
