# Generated by Django 4.2.7 on 2023-11-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0030_alter_leaveapplication_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Half-day leave', 'Half-day leave'), ('One-day leave', 'One-day leave'), ('Earned/Vacation/Privilege Leave', 'Earned/Vacation/Privilege Leave'), ('Sick Leave/Medical Leave', 'Sick Leave/Medical Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity leave', 'Paternity leave'), ('Sabbatical Leave', 'Sabbatical Leave'), ('Bereavement leave', 'Bereavement leave'), ('Compensatory leave', 'Compensatory leave'), ('Compassionate leave', 'Compassionate leave')], max_length=100),
        ),
    ]
