# Generated by Django 4.2.7 on 2023-11-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0031_alter_leaveapplication_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_AO',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_ceo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_director',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_hod',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_principal',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
