# Generated by Django 4.2.7 on 2023-11-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0032_alter_leaveapplication_approved_ao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_AO',
            field=models.IntegerField(blank=True, choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'No Action')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_ceo',
            field=models.IntegerField(blank=True, choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'No Action')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_director',
            field=models.IntegerField(blank=True, choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'No Action')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_hod',
            field=models.IntegerField(blank=True, choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'No Action')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_principal',
            field=models.IntegerField(blank=True, choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'No Action')], default=2, null=True),
        ),
    ]
