# Generated by Django 4.2.7 on 2023-12-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0033_alter_leaveapplication_approved_ao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user_app.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.profile')),
            ],
        ),
    ]
